# Copyright 2024 - 2026 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

require "elastic_graph/proto_ingestion"
require "elastic_graph/proto_ingestion/schema_definition/api_extension"
require "elastic_graph/schema_definition/rake_tasks"
require "yaml"

module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      RSpec.describe "Protobuf RakeTasks", :rake_task, :in_temp_dir do
        describe "schema_artifacts:dump" do
          it "dumps proto artifact when indexed types are defined" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID"
                t.field "name", "String"
                t.index "products"
              end
            EOS

            expect {
              output = run_rake_with_proto("schema_artifacts:dump")
              expect(output.lines).to include(a_string_including("Dumped", PROTO_SCHEMA_FILE))
            }.to change { read_artifact(PROTO_SCHEMA_FILE) }
              .from(nil)
              .to(
                start_with(
                  "// Generated by `bundle exec rake schema_artifacts:dump`.\n" \
                  "// DO NOT EDIT BY HAND. Any edits will be lost the next time the rake task is run.\n"
                ).and(a_string_including('syntax = "proto3";', "message Product", "string name = 2;"))
              )
          end

          it "idempotently dumps proto artifacts" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID"
                t.index "products"
              end
            EOS

            run_rake_with_proto("schema_artifacts:dump")

            expect {
              output = run_rake_with_proto("schema_artifacts:dump")
              expect(output.lines).to include(a_string_including("already up to date", PROTO_SCHEMA_FILE))
            }.to maintain { read_artifact(PROTO_SCHEMA_FILE) }.and maintain { read_proto_field_numbers }
          end

          it "can persist and reuse proto field-number mappings from an artifact file" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID"
                t.field "name", "String"
                t.index "products"
              end
            EOS

            expect {
              run_rake_with_proto("schema_artifacts:dump")
            }.to change { read_proto_field_numbers }
              .from(nil)
              .to(a_string_starting_with("# This file is part of your schema definition"))

            # The file is maintained alongside the schema definition, not in the schema artifacts directory.
            expect(read_artifact(PROTO_FIELD_NUMBERS_FILE)).to be_nil
            expect(parsed_proto_field_numbers).to eq({
              "enums" => {},
              "messages" => {
                "Product" => {
                  "fields" => {
                    "id" => 1,
                    "name" => 2
                  }
                }
              }
            })

            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "name", "String"
                t.field "id", "ID"
                t.index "products"
              end
            EOS

            run_rake_with_proto("schema_artifacts:dump")

            expect(read_artifact(PROTO_SCHEMA_FILE)).to include("string name = 2;")
            expect(read_artifact(PROTO_SCHEMA_FILE)).to include("string id = 1;")
          end
        end

        private

        def write_proto_schema(table_defs:)
          ::File.write("schema.rb", <<~EOS)
            ElasticGraph.define_schema do |s|
              #{table_defs}
            end
          EOS
        end

        def run_rake_with_proto(*args)
          run_rake(*args) do |output|
            ElasticGraph::SchemaDefinition::RakeTasks.new(
              schema_element_name_form: :snake_case,
              index_document_sizes: false,
              path_to_schema: "schema.rb",
              schema_artifacts_directory: "config/schema/artifacts",
              extension_modules: [SchemaDefinition::APIExtension],
              output: output
            )
          end
        end

        def read_artifact(name)
          path = File.join("config", "schema", "artifacts", name)
          File.read(path) if File.exist?(path)
        end

        # The field-numbers file is dumped as a sibling of `path_to_schema` (`schema.rb`, above).
        def read_proto_field_numbers
          File.read(PROTO_FIELD_NUMBERS_FILE) if File.exist?(PROTO_FIELD_NUMBERS_FILE)
        end

        def parsed_proto_field_numbers
          ::YAML.safe_load(read_proto_field_numbers)
        end
      end
    end
  end
end
