module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      module SchemaElements
        module ObjectInterfaceAndUnionExtension : ::ElasticGraph::SchemaDefinition::SchemaElements::ObjectType
          @proto_fields: ::Array[[
            ::ElasticGraph::SchemaDefinition::SchemaElements::Field,
            ::ElasticGraph::SchemaDefinition::Indexing::Field
          ]]?

          def proto_name: () -> ::String
          def proto_type_reference: (::String package_name) -> ::String
          def to_proto: (Schema schema, ::String package_name) -> ::String
          def referenced_proto_types: () -> ::Array[::ElasticGraph::SchemaDefinition::SchemaElements::graphQLType]
          def self.list_depth_and_base_type: (
            ::ElasticGraph::SchemaDefinition::SchemaElements::TypeReference
          ) -> [::Integer, ::ElasticGraph::SchemaDefinition::SchemaElements::TypeReference]

          private

          def render_proto_message: (Schema schema, ::String message_name, ::String package_name) -> ::String
          def render_proto_oneof: (Schema schema, ::String message_name, ::String package_name) -> ::String
          def proto_fields: () -> ::Array[[
            ::ElasticGraph::SchemaDefinition::SchemaElements::Field,
            ::ElasticGraph::SchemaDefinition::Indexing::Field
          ]]
          def proto_field_type_for: (
            ::ElasticGraph::SchemaDefinition::SchemaElements::TypeReference,
            package_name: ::String,
            context_field_name: ::String
          ) -> [bool, ::String]
        end
      end
    end
  end
end
