module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      module SchemaElements
        module ScalarTypeExtension: ::ElasticGraph::SchemaDefinition::SchemaElements::ScalarType
          BUILT_IN_SCALAR_PROTO_TYPES_BY_NAME: ::Hash[::String, ::String]

          attr_reader protobuf_type: ::String?

          def protobuf: (type: ::String) -> void
          def initialize_proto_extension: () { () -> void } -> void
          def proto_name: () -> ::String
          def proto_type_reference: (::String package_name) -> ::String
          def to_proto: (Schema schema, ::String package_name) -> nil
          def referenced_proto_types: () -> ::Array[::ElasticGraph::SchemaDefinition::SchemaElements::graphQLType]
        end
      end
    end
  end
end
