module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      module APIExtension: ::ElasticGraph::SchemaDefinition::API
        def self.extended: (::ElasticGraph::SchemaDefinition::API & APIExtension) -> void
        def proto_schema_artifacts: (
          package_name: ::String,
          ?syntax: (::Symbol | ::String),
          ?headers: ::Array[::String]
        ) -> void

        private

        def proto_ingestion_state: () -> ProtoIngestionState
      end
    end
  end
end
