module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      class ProtoIngestionStateSupertype
        attr_accessor package_name: ::String
        attr_accessor field_number_mappings: untyped

        def initialize: (package_name: ::String, field_number_mappings: untyped) -> void
      end

      class ProtoIngestionState < ProtoIngestionStateSupertype
      end
    end
  end
end
