module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      module SchemaArtifactManagerExtension : ::ElasticGraph::SchemaDefinition::SchemaArtifactManager
        private

        def artifacts_from_schema_def: () -> ::Array[::ElasticGraph::SchemaDefinition::SchemaArtifact[untyped]]
        def proto_field_numbers_artifact: () -> ::ElasticGraph::SchemaDefinition::SchemaArtifact[::Hash[::String, untyped]]
        def proto_field_numbers_path: () -> ::String
        def protobuf_schema_definition_results: () -> (::ElasticGraph::SchemaDefinition::Results & ResultsExtension)
        def proto_ingestion_schema_definition_state: () -> (::ElasticGraph::SchemaDefinition::State & StateExtension)
      end
    end
  end
end
