module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      module SchemaArtifactExtension : ::ElasticGraph::SchemaDefinition::SchemaArtifact[untyped]
        private

        def comment_preamble: () -> ::String
      end
    end
  end
end
