module ElasticGraph
  module SchemaDefinition
    class SchemaArtifactManager
      attr_reader schema_definition_results: Results

      def initialize: (
        schema_definition_results: Results,
        schema_artifacts_directory: ::String,
        output: io,
        ?max_diff_lines: ::Integer
      ) -> void

      def dump_artifacts: () -> void
      def check_artifacts: () -> void

      private

      @schema_definition_results: Results
      @schema_artifacts_directory: ::String
      @output: io
      @max_diff_lines: ::Integer
      @artifacts: ::Array[SchemaArtifact[untyped]]?

      def artifacts: () -> ::Array[SchemaArtifact[untyped]]
      def artifacts_from_schema_def: () -> ::Array[SchemaArtifact[untyped]]
      def notify_about_unused_type_name_overrides: () -> void
      def notify_about_unused_enum_value_overrides: () -> void
      def artifacts_out_of_date_error: (::Array[SchemaArtifact[untyped]]) -> ::String
      def truncate_diff: (::String, ::Integer) -> [::String, ::String]

      def new_yaml_artifact: (
        ::String,
        ::Hash[::String, untyped],
        ?extra_comment_lines: ::Array[::String]
      ) -> SchemaArtifact[::Hash[::String, untyped]]

      def new_raw_artifact: (
        ::String,
        ::String,
        ?comment_prefix: ::String
      ) -> SchemaArtifact[::String]
      def pruned_runtime_metadata: (::String) -> SchemaArtifacts::RuntimeMetadata::Schema
    end

    class SchemaArtifactSupertype[T]
      attr_reader file_name: ::String
      attr_reader desired_contents: T
      attr_reader dumper: ^(T) -> ::String
      attr_reader loader: ^(::String) -> T
      attr_reader extra_comment_lines: ::Array[::String]
      attr_reader comment_prefix: ::String

      def initialize: (
        ::String,
        T,
        ^(T) -> ::String,
        ^(::String) -> T,
        ::Array[::String],
        ::String) -> void

      def with: (?file_name: ::String) -> self
    end

    class SchemaArtifact[T] < SchemaArtifactSupertype[T]
      def dump: (io) -> void
      def out_of_date?: () -> bool
      def existing_dumped_contents: () -> T?
      def diff: (color: bool) -> ::String?

      private

      @exists: bool?
      def exists?: () -> bool

      @dumped_contents: ::String?
      def dumped_contents: () -> ::String
      def comment_preamble: () -> ::String
    end
  end
end
